In [3]:
import pandas as pd 
import numpy as np

In [4]:
df1 = pd.read_csv("FOOD-DATA-GROUP1.csv")
df2 = pd.read_csv("FOOD-DATA-GROUP2.csv")
df3 = pd.read_csv("FOOD-DATA-GROUP3.csv")
df4 = pd.read_csv("FOOD-DATA-GROUP4.csv")
df5 = pd.read_csv("FOOD-DATA-GROUP5.csv")

df = pd.concat([df1,df2,df3,df4,df5], ignore_index=True)

In [8]:
df.head().T

,0,1,2,3,4
Unnamed: 0.1,0,1,2,3,4
Unnamed: 0,0,1,2,3,4
food,cream cheese,neufchatel cheese,requeijao cremoso light catupiry,ricotta cheese,cream cheese low fat
Caloric Value,51,215,49,30,30
Fat,5.0,19.4,3.6,2.0,2.3
Saturated Fats,2.9,10.9,2.3,1.3,1.4
Monounsaturated Fats,1.3,4.9,0.9,0.5,0.6
Polyunsaturated Fats,0.2,0.8,0.0,0.002,0.042
Carbohydrates,0.8,3.1,0.9,1.5,1.2
Sugars,0.5,2.7,3.4,0.091,0.9
Protein,0.9,7.8,0.8,1.5,1.2
Dietary Fiber,0.0,0.0,0.1,0.0,0.0
Cholesterol,14.6,62.9,0.0,9.8,8.1
Sodium,0.016,0.3,0.0,0.017,0.046
Water,7.6,53.6,0.0,14.7,10.0
Vitamin A,0.2,0.2,0.0,0.075,0.016
Vitamin B1,0.033,0.099,0.0,0.019,0.08
Vitamin B11,0.064,0.079,0.0,0.079,0.062
Vitamin B12,0.092,0.09,0.0,0.091,0.049
Vitamin B2,0.097,0.1,0.0,0.027,0.026
Vitamin B3,0.084,0.2,0.0,0.041,0.08
Vitamin B5,0.052,0.5,0.0,0.016,0.1
Vitamin B6,0.096,0.078,0.0,0.007,0.003
Vitamin C,0.004,0.0,0.0,0.006,0.0
Vitamin D,0.0,0.0,0.0,0.0,0.036
Vitamin E,0.0,0.3,0.0,0.001,0.009
Vitamin K,0.1,0.045,0.0,0.011,0.019
Calcium,0.008,99.5,0.0,0.097,22.2
Copper,14.1,0.034,0.0,41.2,0.072
Iron,0.082,0.1,0.0,0.097,0.008
Magnesium,0.027,8.5,0.0,0.096,1.2
Manganese,1.3,0.088,0.0,4.0,0.098
Phosphorus,0.091,117.3,0.0,0.024,22.8
Potassium,15.5,129.2,0.0,30.8,37.1
Selenium,19.1,0.054,0.0,43.8,0.034
Zinc,0.039,0.7,0.0,0.035,0.053
Nutrition Density,7.07,130.1,5.4,5.196,27.007

In [9]:
df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])

In [11]:
df.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [24]:
df[['food', 'Caloric Value']].sort_values(by='Caloric Value', ascending=False).head()

                                food  Caloric Value
1418                chicken meat raw      1687.0684
1385  pork centre rib roasts roasted      1687.0684
1389           pork backribs roasted      1687.0684
1390                  pork belly raw      1687.0684
1372                    pork backfat      1687.0684

In [19]:
calorie_cap = df['Caloric Value'].quantile(0.99)
df['Caloric Value'] = np.where(
    df['Caloric Value'] > calorie_cap,
    calorie_cap,
    df['Caloric Value']
)

# Step 2: Replace 0 calorie entries with average of min positive & max (capped) calorie
min_nonzero = df[df['Caloric Value'] > 0]['Caloric Value'].min()
avg_impute_value = (min_nonzero + calorie_cap) / 2

df['Caloric Value'] = df['Caloric Value'].replace(0, avg_impute_value)

In [21]:
df[['food', 'Caloric Value']].sort_values(by='Caloric Value', ascending=False).head()

                                food  Caloric Value
1418                chicken meat raw      1687.0684
1385  pork centre rib roasts roasted      1687.0684
1389           pork backribs roasted      1687.0684
1390                  pork belly raw      1687.0684
1372                    pork backfat      1687.0684

In [23]:
df[df['Caloric Value'] > 800]

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
17,gjetost cheese,1058.00,67.000,43.500,17.900,2.100,96.800,0.000,21.900,0.000,...,908.000,0.200,1.200,158.900,0.035,1007.900,3198.4,0.039,2.600,1095.700
83,lemon chicken,1440.00,74.900,12.200,16.400,36.700,122.000,55.200,68.600,7.000,...,248.400,0.200,8.400,95.600,0.600,821.700,987.4,0.001,3.200,545.212
153,general tsos chicken,1578.00,87.500,14.800,20.800,40.100,128.300,62.100,69.000,4.800,...,64.200,0.200,6.200,96.300,0.400,679.500,1075.4,0.065,7.000,368.673
306,double hamburger,942.00,58.600,21.600,22.900,11.300,51.400,13.200,52.100,5.200,...,0.094,130.900,0.400,10.500,67.300,0.700,415.1,718.100,0.026,169.626
317,double whopper with cheese burger king,1061.00,68.100,27.900,25.100,11.900,53.900,14.400,57.700,6.400,...,311.200,0.300,21.100,75.800,0.600,510.700,754.1,0.075,14.000,519.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1942,potato chips sour cream and onion,1051.00,67.100,17.600,12.100,34.500,102.000,0.000,16.000,10.300,...,142.600,0.600,3.200,146.500,0.800,348.500,2635.4,0.000,1.900,415.171
2080,soybean raw,830.00,37.100,5.400,8.200,20.900,56.100,13.600,67.900,17.300,...,515.200,3.100,29.200,520.800,4.700,1309.400,3342.4,0.071,9.100,734.000
2233,lambs quarters raw,844.57,0.067,0.000,0.000,0.000,0.069,0.000,0.080,0.046,...,3.300,0.045,0.060,1.500,0.076,0.600,11.4,0.052,0.080,3.658
2366,taco salad taco bell,906.00,48.900,15.900,21.200,4.000,80.500,0.000,35.700,16.000,...,506.400,0.800,9.400,143.900,1.400,549.000,1220.6,0.095,6.200,696.900
2383,maitake mushrooms,844.57,0.017,0.011,0.059,0.022,0.072,0.043,0.016,0.041,...,0.000,0.063,0.013,0.088,0.100,0.082,0.8,2.200,0.035,0.374

In [31]:
import numpy as np

# Define reasonable kcal range for 100g: typically 30 to 600
min_kcal, max_kcal = 30, 600

# Clip calories to the range and rescale macros accordingly
def standardize_to_100g(row):
    calories = row['Caloric Value']
    
    # Clip calories
    clipped_cal = np.clip(calories, min_kcal, max_kcal)
    
    # Scale factor
    scale = clipped_cal / calories if calories > 0 else 1

    # Scale macros
    row['Caloric Value'] = clipped_cal
    row['Protein'] *= scale
    row['Fat'] *= scale
    row['Carbohydrates'] *= scale
    return row

merged_food_df = df.apply(standardize_to_100g, axis=1)

In [32]:
merged_food_df[['food', 'Caloric Value']].sort_values(by='Caloric Value', ascending=False).head()

                      food  Caloric Value
17          gjetost cheese          600.0
1418      chicken meat raw          600.0
2366  taco salad taco bell          600.0
1417       chicken leg raw          600.0
1943          adobo fresco          600.0